# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: microsoft/dotnet:2.1-sdk-alpine

variables:
  project_name: Kveer.XmlRPC
  configuration: Release

build-master:
  stage: build
  script:
    - cd "${project_name}"
    - dotnet restore "${project_name}.csproj"
    - dotnet build -c "${configuration}" "${project_name}.csproj"
    - dotnet pack -c "${configuration}" --include-symbols "${project_name}.csproj"
#    - dotnet nuget push bin/"${configuration}"/*.nupkg -k $nuget_key -s nuget.org
#    - dotnet nuget push bin/"${configuration}"/*.symbols.nupkg -k $nuget_key -s https://nuget.smbsrc.net/
  only:
    - master

sast:
  image: docker:-dind
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
        --volume "$PWD/${project_name}:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  artifacts:
    paths: [gl-sast-report.json]
